# REST API Server on Local Firebase
# @baseUrl = http://localhost:5001/projectmap-f4c90/us-central1/api

# REST API Server on Live Firebase
 @baseUrl = https://us-central1-projectmap-f4c90.cloudfunctions.net/api


### Getting the list of selling
GET {{baseUrl}}/selling

### Getting the list of event
GET {{baseUrl}}/event

### Getting the list of confession
GET {{baseUrl}}/confession

###  Getting a selling of given id
GET {{baseUrl}}/confession/7ohXHBzLaqlg2l1QHb8R

###  Create a new selling
POST {{baseUrl}}/selling/
Content-Type: application/json

{
    "prodName": "Jasim", 
    "prodPrice": "RM 50.00", 
    "prodDesc": "Classic pen ,convenient to write and must to be own one s"

}

###  Create a new event
POST {{baseUrl}}/event/
Content-Type: application/json

{
    "eventName": "FESKO", 
    "venue": "Padang KAWAD", 
    "time": "10/10/2020-17/10/2020", 
    "description": "Fiesta Konvokesyen held in order to celebrate the students being graduated"
}

###  Create a new confession
POST {{baseUrl}}/confession/
Content-Type: application/json

{
    "username": "Jasim", 
    "subject": "Fight at Arked Lestari", 
    "content": "There was a fight between shop staff and UTM student at arked lestari due to food was served late"

}
### Update the status of a given selling 
PATCH {{baseUrl}}/event/0r1LjdDLIPGeoWbT7NBr
Content-Type: application/json

{
    "time": "10/10/2020-15/10/2020"
}


### Replace the entire fields of a given selling
PUT {{baseUrl}}/selling/sQ9efkAJlws6KMfCjcKo
Content-Type: application/json

{
    "prodPrice": "RM 60.00"
}

### Deleting a given selling
DELETE {{baseUrl}}/selling/YqoainV4mkMan2lKNfuk